<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250203235619 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add log_entries table';
    }


    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE log_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(8) NOT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(191) NOT NULL, version INT NOT NULL, data JSON DEFAULT NULL, username VARCHAR(191) DEFAULT NULL, PRIMARY KEY(id))',
        );
        $this->addSql('CREATE INDEX log_class_lookup_idx ON log_entries (object_class)');
        $this->addSql('CREATE INDEX log_date_lookup_idx ON log_entries (logged_at)');
        $this->addSql('CREATE INDEX log_user_lookup_idx ON log_entries (username)');
        $this->addSql('CREATE INDEX log_version_lookup_idx ON log_entries (object_id, object_class, version)');
    }


    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE log_entries');
    }
}
